### ISSUE TITLE
Configure option not showing up in tacklebox

### ISSUE THREAD

**Issue by spsw101** [elliotcubit/WebfishingButtplug#5]
Having a weird issue where the mod shows up in tacklebox but there is no configure option.

The mod vibrates during the fishing game as it did in older versions of the mod, but the lack of config button means I cannot adjust base intensity.  It also does not appear to vibrate during scratch offs.

GDWeave, Intiface, Tacklebox, and Webfishing Buttplug are all the most recent versions of their respective mods.

A friend of mine who runs the mod fine tried to help me out but neither of us are technologically competent and could not make heads or tails of the situation.

Thanks for your assistance.

**Comment by angus-lherrou** [comment]
I am having the same problem.

**Comment by oniondip420** [comment]
Likewise, I am not seeing any configure button in the Mods menu. I only just installed the mod so I didn't have previous settings, and it seems I cannot get my device to activate at all (even though I know Intiface is connected to it).

EDIT: Attempting with other versions of this mod still had it show up in TackleBox, but none of them showed a configure button. Wondering if maybe it has something to do with TackleBox instead, I reverted ButtPlugIO back to its latest version (1.3.0) and changed TackleBox to the previous one from last week (0.5.0). Still no luck. Not sure where the problem is originating.

**Comment by elliotcubit** [comment]
Is there anything relevant in the GDWeave logs? I'm looking into this issue, but I can't reproduce it (even on a clean install)

**Comment by elliotcubit** [comment]
Perhaps if you make a `ButtPlugIO.json` in your `config` folder manually it will appear?

**Comment by spsw101** [comment]
> Is there anything relevant in the GDWeave logs? I'm looking into this issue, but I can't reproduce it (even on a clean install)

This is my log.  My friend and I looked at it but nothing stood out to us.

[GDWeave.log](https://github.com/user-attachments/files/17822668/GDWeave.log)

**Comment by oniondip420** [comment]
Perhaps if you make a `ButtPlugIO.json` in your `config` folder manually it will appear?

_Originally posted by @elliotcubit in https://github.com/elliotcubit/WebfishingButtplug/issues/5#issuecomment-2486926021_
            
What folder are you referring to? I don't seem to have a config folder in my install. My directory structure looks like:

- .../steamapps/common/WEBFISHING
    - GDWeave
        - core
        - mods
            - ButtPlugIO
            - TackleBox

I don't have any folder named `config`, is that something I should manually add?

My own log file is attached too, which is also not very helpful since it just says that it successfully loaded the mods.
[GDWeave.log](https://github.com/user-attachments/files/17823430/GDWeave.log)

EDIT: Whoopsie ignore the other issue I accidentally opened!

**Comment by elliotcubit** [comment]
I would expect a folder called `configs` under `GDWeave`. Try and manually create it?
![image](https://github.com/user-attachments/assets/87a7b6be-fa28-446b-ae2f-d91b75b18dff)

**Comment by elliotcubit** [comment]
Pretty confidence this is the issue - I'm able to reproduce it locally. Manually create a `configs` folder in your `GDWeave` directory; this will allow you to configure the mod.

I think this is a bug in TackleBox.

**Comment by oniondip420** [comment]
That immediately fixed it for me!!! Thank you!! Should I report this as a bug for TackleBox as follow up? If it is that mod's job to create the configs folder, then certainly something is wrong there.

**Comment by elliotcubit** [comment]
I'm working on a pull request for TackleBox to fix the issue. :) Thank you

**Comment by spsw101** [comment]
> Pretty confidence this is the issue - I'm able to reproduce it locally. Manually create a `configs` folder in your `GDWeave` directory; this will allow you to configure the mod.
> 
> I think this is a bug in TackleBox.

This fixed it for me as well.  Thank you!
